# Generated by Django 2.2.7 on 2020-02-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
