# Generated by Django 2.2.7 on 2020-03-21 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room', models.ForeignKey(on_delete=False, related_name='roomuser_roomid', to='chat.ChatRoom')),
                ('user', models.ForeignKey(on_delete=False, related_name='roomuser_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('chat_room', models.ForeignKey(on_delete=False, related_name='message_roomid', to='chat.ChatRoom')),
                ('user', models.ForeignKey(on_delete=False, related_name='message_userid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
